import type { PermissionDefinition, PermissionLevel } from '../types';

function p(module: string, resource: string, action: string, level: PermissionLevel = 'endpoint', description = '', category?: string): PermissionDefinition {
  return { code: `${module}.${resource}.${action}`, module, resource, action, level, description, category };
}

/**
 * Sub-resource -> UI category label, admin module only (see
 * .ai/ADMIN_UI_ACCESS_CONTROL_SPEC.md Section 2.1). Verified against the real
 * `resource` strings already used by `p('admin', ...)` calls below, not the
 * spec's illustrative resource names (some differ, e.g. `bulk-ops` not
 * `bulk-operation`, `delegations` not `delegation`, `alerts` not `alert`).
 * Every non-admin module leaves `category` undefined and keeps flat grouping.
 */
function admin(resource: string, action: string, level: PermissionLevel, description: string, category: string): PermissionDefinition {
  return p('admin', resource, action, level, description, category);
}

export const PERMISSION_REGISTRY: PermissionDefinition[] = [
  // Admin
  admin('user', 'read', 'endpoint', 'View users', 'Users & Roles'),
  admin('user', 'create', 'endpoint', 'Create users', 'Users & Roles'),
  admin('user', 'update', 'endpoint', 'Update users', 'Users & Roles'),
  admin('user', 'delete', 'endpoint', 'Delete users', 'Users & Roles'),
  admin('role', 'read', 'endpoint', 'View roles', 'Users & Roles'),
  admin('role', 'create', 'endpoint', 'Create roles', 'Users & Roles'),
  admin('role', 'update', 'endpoint', 'Update roles', 'Users & Roles'),
  admin('role', 'delete', 'endpoint', 'Delete roles', 'Users & Roles'),
  admin('access-package', 'read', 'endpoint', 'View access packages', 'Users & Roles'),
  admin('access-package', 'create', 'endpoint', 'Create access packages', 'Users & Roles'),
  admin('access-package', 'update', 'endpoint', 'Update access packages', 'Users & Roles'),
  admin('access-package', 'delete', 'endpoint', 'Delete access packages', 'Users & Roles'),
  admin('setting', 'read', 'endpoint', 'View settings', 'General Settings'),
  admin('setting', 'create', 'endpoint', 'Create settings', 'General Settings'),
  admin('setting', 'update', 'endpoint', 'Update settings', 'General Settings'),
  admin('localization', 'read', 'endpoint', 'View translations', 'General Settings'),
  admin('localization', 'create', 'endpoint', 'Create translations', 'General Settings'),
  admin('localization', 'delete', 'endpoint', 'Delete translations', 'General Settings'),
  admin('demo', 'manage', 'endpoint', 'Load/remove demo data', 'General Settings'),
  admin('user-group', 'read', 'endpoint', 'View user groups', 'User Groups'),
  admin('user-group', 'create', 'endpoint', 'Create user groups', 'User Groups'),
  admin('user-group', 'update', 'endpoint', 'Update user groups', 'User Groups'),
  admin('user-group', 'delete', 'endpoint', 'Delete user groups', 'User Groups'),
  admin('security', 'read', 'endpoint', 'View security audit logs, sessions, MFA, SSO, password policy', 'Security'),
  admin('security', 'update', 'endpoint', 'Manage security settings, sessions, MFA, SSO, password policy', 'Security'),
  admin('automation', 'read', 'endpoint', 'View automation rules', 'Automation'),
  admin('automation', 'create', 'endpoint', 'Create automation rules', 'Automation'),
  admin('automation', 'update', 'endpoint', 'Update/test automation rules', 'Automation'),
  admin('automation', 'delete', 'endpoint', 'Delete automation rules', 'Automation'),
  admin('platform', 'read', 'endpoint', 'View platform settings, modules, feature flags, marketplace', 'Platform'),
  admin('platform', 'update', 'endpoint', 'Manage platform settings, modules, feature flags, marketplace', 'Platform'),
  admin('operations', 'read', 'endpoint', 'View operations dashboard, jobs, logs, backups', 'Operations'),
  admin('operations', 'update', 'endpoint', 'Manage operations: retry jobs, trigger tasks, create backups', 'Operations'),
  admin('org-hierarchy', 'read', 'endpoint', 'View org hierarchy, departments, cost centers', 'Org Hierarchy'),
  admin('org-hierarchy', 'create', 'endpoint', 'Create departments and cost centers', 'Org Hierarchy'),
  admin('org-hierarchy', 'update', 'endpoint', 'Update departments and cost centers', 'Org Hierarchy'),
  admin('org-hierarchy', 'delete', 'endpoint', 'Delete departments and cost centers', 'Org Hierarchy'),
  admin('bulk-ops', 'read', 'endpoint', 'View bulk operations', 'Bulk Operations'),
  admin('bulk-ops', 'create', 'endpoint', 'Create bulk operations', 'Bulk Operations'),
  admin('custom-fields', 'read', 'endpoint', 'View custom field definitions and values', 'Custom Fields'),
  admin('custom-fields', 'create', 'endpoint', 'Create custom field definitions', 'Custom Fields'),
  admin('custom-fields', 'update', 'endpoint', 'Update custom field definitions and values', 'Custom Fields'),
  admin('custom-fields', 'delete', 'endpoint', 'Delete custom field definitions', 'Custom Fields'),
  admin('data-quality', 'read', 'endpoint', 'View duplicate detection results', 'Data Quality'),
  admin('data-quality', 'update', 'endpoint', 'Scan, merge, and dismiss duplicate records', 'Data Quality'),
  admin('delegations', 'read', 'endpoint', 'View delegation rules', 'Delegation'),
  admin('delegations', 'create', 'endpoint', 'Create delegation rules', 'Delegation'),
  admin('delegations', 'update', 'endpoint', 'Update/revoke delegation rules', 'Delegation'),
  admin('recycle-bin', 'read', 'endpoint', 'View recycle bin items and stats', 'Recycle Bin'),
  admin('recycle-bin', 'update', 'endpoint', 'Restore recycle bin items', 'Recycle Bin'),
  admin('recycle-bin', 'delete', 'endpoint', 'Permanently delete or purge recycle bin items', 'Recycle Bin'),
  admin('subscription', 'read', 'endpoint', 'View subscription plan and billing history', 'Subscription'),
  admin('subscription', 'update', 'endpoint', 'Change subscription plan or seats', 'Subscription'),
  admin('alerts', 'read', 'endpoint', 'View alerts and alert thresholds', 'Alerts'),
  admin('alerts', 'update', 'endpoint', 'Mark/dismiss alerts and manage thresholds', 'Alerts'),

  // Finance
  p('finance', 'invoice', 'read', 'endpoint', 'View invoices'),
  p('finance', 'invoice', 'create', 'endpoint', 'Create invoices'),
  p('finance', 'invoice', 'update', 'endpoint', 'Update invoices'),
  p('finance', 'invoice', 'delete', 'endpoint', 'Delete invoices'),
  p('finance', 'invoice', 'send', 'endpoint', 'Send invoices'),
  p('finance', 'invoice', 'void', 'endpoint', 'Void invoices'),
  p('finance', 'invoice', 'amount', 'field', 'View invoice amounts'),
  p('finance', 'payment', 'read', 'endpoint', 'View payments'),
  p('finance', 'payment', 'create', 'endpoint', 'Create payments'),
  p('finance', 'account', 'read', 'endpoint', 'View accounts'),
  p('finance', 'account', 'create', 'endpoint', 'Create accounts'),
  p('finance', 'report', 'read', 'endpoint', 'View finance reports'),
  p('finance', 'report', 'export', 'endpoint', 'Export finance reports'),
  p('finance', 'journal', 'read', 'endpoint', 'View journals'),
  p('finance', 'journal', 'create', 'endpoint', 'Create journals'),
  p('finance', 'journal', 'approve', 'endpoint', 'Approve/post journals'),
  p('finance', 'journal', 'reverse', 'endpoint', 'Reverse journals'),
  p('finance', 'budget', 'read', 'endpoint', 'View budgets'),
  p('finance', 'budget', 'create', 'endpoint', 'Create budgets'),
  p('finance', 'budget', 'update', 'endpoint', 'Update budgets'),
  p('finance', 'budget', 'delete', 'endpoint', 'Delete budgets'),
  p('finance', 'bank-account', 'read', 'endpoint', 'View bank accounts'),
  p('finance', 'bank-account', 'create', 'endpoint', 'Create bank accounts'),
  p('finance', 'bank-account', 'update', 'endpoint', 'Update bank accounts'),
  p('finance', 'bank-recon', 'read', 'endpoint', 'View bank reconciliations'),
  p('finance', 'bank-recon', 'create', 'endpoint', 'Create bank reconciliations'),
  p('finance', 'bank-recon', 'match', 'endpoint', 'Perform bank transaction matching'),
  p('finance', 'expense', 'read', 'endpoint', 'View expense reports'),
  p('finance', 'expense', 'create', 'endpoint', 'Create expense reports'),
  p('finance', 'expense', 'approve', 'endpoint', 'Approve expense reports'),
  p('finance', 'expense', 'reject', 'endpoint', 'Reject expense reports'),
  p('finance', 'report', 'create', 'endpoint', 'Generate/save finance reports'),
  p('finance', 'reports', 'read', 'endpoint', 'View finance report dashboards'),
  p('finance', 'credit', 'read', 'endpoint', 'View customer credit risk data'),
  p('finance', 'credit', 'manage', 'endpoint', 'Manage customer credit limits/holds/ratings'),
  p('finance', 'tax', 'read', 'endpoint', 'View tax rules/filings/notes'),
  p('finance', 'tax', 'create', 'endpoint', 'Create tax rules/filings/notes'),
  p('finance', 'tax', 'update', 'endpoint', 'Update tax rules/filings/notes'),
  p('finance', 'tax', 'delete', 'endpoint', 'Delete tax rules/filings/notes'),
  p('finance', 'tax', 'compute', 'endpoint', 'Compute tax returns'),
  p('finance', 'period', 'read', 'endpoint', 'View financial periods'),
  p('finance', 'period', 'create', 'endpoint', 'Create financial periods'),
  p('finance', 'period', 'close', 'endpoint', 'Close/reopen financial periods'),
  p('finance', 'consolidation', 'read', 'endpoint', 'View consolidations'),
  p('finance', 'consolidation', 'run', 'endpoint', 'Run consolidations'),
  p('finance', 'treasury', 'read', 'endpoint', 'View treasury and portfolios'),
  p('finance', 'treasury', 'create', 'endpoint', 'Manage treasury transactions and transfers'),
  p('finance', 'einvoice', 'read', 'endpoint', 'View e-invoices'),
  p('finance', 'einvoice', 'generate', 'endpoint', 'Generate e-invoices'),
  p('finance', 'audit', 'read', 'endpoint', 'View finance audit logs'),
  p('finance', 'books', 'manage', 'endpoint', 'Manage accounting books and mapping rules'),
  p('finance', 'revenue', 'read', 'endpoint', 'View revenue schedules'),
  p('finance', 'revenue', 'create', 'endpoint', 'Create revenue schedules'),
  p('finance', 'revenue', 'recognize', 'endpoint', 'Recognize revenue'),
  p('finance', 'subscription', 'read', 'endpoint', 'View subscriptions (billing, MRR, usage)'),
  p('finance', 'subscription', 'create', 'endpoint', 'Create subscriptions'),
  p('finance', 'subscription', 'update', 'endpoint', 'Update subscriptions'),
  p('finance', 'subscription', 'delete', 'endpoint', 'Delete subscriptions'),
  p('finance', 'subscription', 'manage', 'endpoint', 'Manage subscription lifecycle (activate, cancel, change plan)'),
  p('finance', 'corporate-card-limit', 'read', 'endpoint', 'View corporate card spend/category limits, utilization, and audit trail'),
  p('finance', 'corporate-card-limit', 'create', 'endpoint', 'Create corporate card spend limits'),
  p('finance', 'corporate-card-limit', 'update', 'endpoint', 'Update corporate card spend/category limits'),
  p('finance', 'corporate-card-limit', 'delete', 'endpoint', 'Delete corporate card spend limits'),
  p('finance', 'corporate-card-limit', 'request-increase', 'endpoint', 'Request a corporate card spend limit increase'),
  p('finance', 'corporate-card-limit', 'approve', 'endpoint', 'Approve a corporate card spend limit increase request'),
  p('finance', 'corporate-card', 'freeze', 'endpoint', 'Freeze/unfreeze a corporate card'),
  // Finance — compliance (internal controls, SoD, period certifications, audit confirmations)
  p('finance', 'compliance', 'read', 'endpoint', 'View compliance controls, tests, SoD rules, audit confirmations'),
  p('finance', 'compliance', 'create', 'endpoint', 'Create compliance controls, tests, SoD rules'),
  p('finance', 'compliance', 'update', 'endpoint', 'Update compliance controls and respond to confirmations'),
  p('finance', 'compliance', 'delete', 'endpoint', 'Deactivate compliance controls'),
  // Finance — fixed asset lifecycle (revaluations, disposals, audit reports)
  p('finance', 'fixed-asset', 'read', 'endpoint', 'View fixed asset revaluations, disposals, and audit reports'),
  p('finance', 'fixed-asset', 'create', 'endpoint', 'Create fixed asset revaluations and disposals'),

  // HR
  p('hr', 'employee', 'read', 'endpoint', 'View employees'),
  p('hr', 'employee', 'create', 'endpoint', 'Create employees'),
  p('hr', 'employee', 'update', 'endpoint', 'Update employees'),
  p('hr', 'employee', 'delete', 'endpoint', 'Delete employees'),
  p('hr', 'employee', 'salary', 'field', 'View employee salary'),
  p('hr', 'department', 'read', 'endpoint', 'View departments'),
  p('hr', 'department', 'create', 'endpoint', 'Create departments'),
  p('hr', 'payroll', 'read', 'endpoint', 'View payroll'),
  p('hr', 'payroll', 'create', 'endpoint', 'Process payroll'),
  p('hr', 'payroll', 'approve', 'endpoint', 'Approve payroll'),
  p('hr', 'leave', 'read', 'endpoint', 'View leave requests'),
  p('hr', 'leave', 'approve', 'endpoint', 'Approve leave requests'),
  p('hr', 'attendance', 'read', 'endpoint', 'View attendance'),

  // CRM
  p('crm', 'contact', 'read', 'endpoint', 'View contacts'),
  p('crm', 'contact', 'create', 'endpoint', 'Create contacts'),
  p('crm', 'contact', 'update', 'endpoint', 'Update contacts'),
  p('crm', 'contact', 'delete', 'endpoint', 'Delete contacts'),
  p('crm', 'lead', 'read', 'endpoint', 'View leads'),
  p('crm', 'lead', 'create', 'endpoint', 'Create leads'),
  p('crm', 'lead', 'update', 'endpoint', 'Update leads'),
  p('crm', 'lead', 'delete', 'endpoint', 'Delete leads'),
  p('crm', 'lead', 'convert', 'endpoint', 'Convert leads'),
  p('crm', 'opportunity', 'read', 'endpoint', 'View opportunities'),
  p('crm', 'opportunity', 'create', 'endpoint', 'Create opportunities'),
  p('crm', 'opportunity', 'update', 'endpoint', 'Update opportunities'),
  p('crm', 'activity', 'read', 'endpoint', 'View activities'),
  p('crm', 'activity', 'create', 'endpoint', 'Create activities'),
  p('crm', 'case', 'read', 'endpoint', 'View customer service cases'),
  p('crm', 'case', 'create', 'endpoint', 'Create customer service cases'),
  p('crm', 'case', 'update', 'endpoint', 'Update customer service cases'),
  p('crm', 'mailbox', 'read', 'endpoint', 'Read crm mailbox'),
  p('crm', 'mailbox', 'create', 'endpoint', 'Create crm mailbox items'),
  p('crm', 'mailbox', 'delete', 'endpoint', 'Delete crm mailbox items'),
  p('crm', 'mailbox', 'update', 'endpoint', 'Update crm mailbox items'),
  p('crm', 'customer', 'read', 'endpoint', 'View customers'),
  p('crm', 'customer', 'update', 'endpoint', 'Update customers'),
  p('crm', 'customer-portal', 'manage', 'endpoint', 'Manage customer self-service portal accounts'),
  p('crm', 'campaign', 'read', 'endpoint', 'View marketing campaigns'),
  p('crm', 'playbook', 'read', 'endpoint', 'View sales enablement playbooks'),
  p('crm', 'sales-target', 'read', 'endpoint', 'View sales targets'),
  p('crm', 'sales-target', 'update', 'endpoint', 'Update sales targets'),
  p('crm', 'commission', 'read', 'endpoint', 'View RevOps commissions'),
  p('crm', 'partner', 'read', 'endpoint', 'View partners'),
  p('crm', 'workflow', 'read', 'endpoint', 'View automated workflows'),
  // Contract permissions: see `p('crm', 'contracts', ...)` further down
  // (resource is plural `contracts` there, matching the actual
  // `@Permissions('crm.contracts.*')` codes used by crm-contracts.controller.ts).

  // E-Commerce Storefront (module #33) — admin-side only. Public `/store/:tenantSlug/*`
  // routes are an intentional, documented exception to Rule 15 (no @Permissions) —
  // see .ai/ECOMMERCE_MODULE_REQUIREMENTS.md Section 7 and .ai/DATA_MODEL.md Section 3.4.
  p('ecommerce', 'storefront', 'read', 'endpoint', 'View storefront configuration'),
  p('ecommerce', 'storefront', 'manage', 'endpoint', 'Enable/disable storefront and edit settings'),
  p('ecommerce', 'listing', 'read', 'endpoint', 'View product listings'),
  p('ecommerce', 'listing', 'create', 'endpoint', 'Publish products to storefront'),
  p('ecommerce', 'listing', 'update', 'endpoint', 'Update storefront listing (price override, sort, category)'),
  p('ecommerce', 'listing', 'delete', 'endpoint', 'Unpublish a storefront listing'),
  p('ecommerce', 'category', 'read', 'endpoint', 'View storefront categories'),
  p('ecommerce', 'category', 'create', 'endpoint', 'Create storefront categories'),
  p('ecommerce', 'category', 'update', 'endpoint', 'Update storefront categories'),
  p('ecommerce', 'category', 'delete', 'endpoint', 'Delete storefront categories'),
  p('ecommerce', 'order', 'read', 'endpoint', 'View storefront (online-channel) orders'),

  // Inventory
  p('inventory', 'product', 'read', 'endpoint', 'View products'),
  p('inventory', 'product', 'create', 'endpoint', 'Create products'),
  p('inventory', 'product', 'update', 'endpoint', 'Update products'),
  p('inventory', 'product', 'delete', 'endpoint', 'Delete products'),
  p('inventory', 'warehouse', 'read', 'endpoint', 'View warehouses'),
  p('inventory', 'warehouse', 'create', 'endpoint', 'Create warehouses'),
  p('inventory', 'stock', 'read', 'endpoint', 'View stock'),
  p('inventory', 'stock', 'adjust', 'endpoint', 'Adjust stock'),
  p('inventory', 'stock', 'transfer', 'endpoint', 'Transfer stock'),

  // Procurement
  p('procurement', 'vendor', 'read', 'endpoint', 'View vendors'),
  p('procurement', 'vendor', 'create', 'endpoint', 'Create vendors'),
  p('procurement', 'vendor', 'update', 'endpoint', 'Update vendors'),
  p('procurement', 'vendor', 'delete', 'endpoint', 'Delete vendors'),
  p('procurement', 'purchase-order', 'read', 'endpoint', 'View purchase orders'),
  p('procurement', 'purchase-order', 'create', 'endpoint', 'Create purchase orders'),
  p('procurement', 'purchase-order', 'approve', 'endpoint', 'Approve purchase orders'),
  p('procurement', 'rfq', 'read', 'endpoint', 'View RFQs'),
  p('procurement', 'rfq', 'create', 'endpoint', 'Create RFQs'),

  // Sales
  p('sales', 'quotation', 'read', 'endpoint', 'View quotations'),
  p('sales', 'quotation', 'create', 'endpoint', 'Create quotations'),
  p('sales', 'quotation', 'send', 'endpoint', 'Send quotations'),
  p('sales', 'sales-order', 'read', 'endpoint', 'View sales orders'),
  p('sales', 'sales-order', 'create', 'endpoint', 'Create sales orders'),
  p('sales', 'sales-order', 'confirm', 'endpoint', 'Confirm sales orders'),
  p('sales', 'return', 'read', 'endpoint', 'View returns'),
  p('sales', 'return', 'create', 'endpoint', 'Create returns'),
  p('sales', 'return', 'approve', 'endpoint', 'Approve returns'),
  // Sales — 2-segment legacy codes used by sales.controller.ts (not matching p() naming)
  { code: 'sales.delivery-note.read', module: 'sales', resource: 'delivery-note', action: 'read', level: 'endpoint', description: 'View delivery notes' },
  { code: 'sales.delivery-note.create', module: 'sales', resource: 'delivery-note', action: 'create', level: 'endpoint', description: 'Create delivery notes' },
  { code: 'sales.delivery-note.update', module: 'sales', resource: 'delivery-note', action: 'update', level: 'endpoint', description: 'Update delivery notes' },
  { code: 'sales.return.update', module: 'sales', resource: 'return', action: 'update', level: 'endpoint', description: 'Update returns' },
  { code: 'sales.order.read', module: 'sales', resource: 'order', action: 'read', level: 'endpoint', description: 'View sales orders (legacy code)' },

  // Manufacturing
  p('manufacturing', 'bom', 'read', 'endpoint', 'View BOMs'),
  p('manufacturing', 'bom', 'create', 'endpoint', 'Create BOMs'),
  p('manufacturing', 'work-order', 'read', 'endpoint', 'View work orders'),
  p('manufacturing', 'work-order', 'create', 'endpoint', 'Create work orders'),

  // Communication (Connect) — coarse legacy strings still used by some controller routes.
  // These are genuinely 2-segment codes at runtime (`communication.read`, not
  // `communication.general.read`) — verified by grepping every @Permissions(...) string in
  // communication.controller.ts. Declared as literal PermissionDefinitions (not via the `p()`
  // helper, which always emits a 3-segment `module.resource.action` code) so the registry entry
  // exactly matches what RbacGuard actually checks; a near-miss code here would leave these four
  // permissions invisible to the Access Control admin UI despite "existing" in this file.
  { code: 'communication.read', module: 'communication', resource: 'general', action: 'read', level: 'endpoint', description: 'View communication module (legacy coarse permission)' },
  { code: 'communication.create', module: 'communication', resource: 'general', action: 'create', level: 'endpoint', description: 'Create in communication module (legacy coarse permission)' },
  { code: 'communication.update', module: 'communication', resource: 'general', action: 'update', level: 'endpoint', description: 'Update in communication module (legacy coarse permission)' },
  { code: 'communication.delete', module: 'communication', resource: 'general', action: 'delete', level: 'endpoint', description: 'Delete in communication module (legacy coarse permission)' },
  // Communication (Connect) — fine-grained resource permissions enforced by RbacGuard
  p('communication', 'channel', 'read', 'endpoint', 'View channels and workspace'),
  p('communication', 'channel', 'create', 'endpoint', 'Create channels, spaces, DMs and groups'),
  p('communication', 'channel', 'manage', 'endpoint', 'Rename or archive channels'),
  p('communication', 'channel', 'join', 'endpoint', 'Join public channels'),
  p('communication', 'channel.member', 'manage', 'endpoint', 'Add or remove channel members'),
  p('communication', 'message', 'read', 'endpoint', 'View messages'),
  p('communication', 'message', 'create', 'endpoint', 'Send, edit, delete, react to messages'),
  p('communication', 'message', 'search', 'endpoint', 'Search message content across joined channels'),
  p('communication', 'message-attachment', 'upload', 'endpoint', 'Upload a file attachment to a Connect message'),
  p('communication', 'notification', 'read', 'endpoint', 'View notifications'),
  p('communication', 'notification', 'create', 'endpoint', 'Create notifications'),
  p('communication', 'notification', 'update', 'endpoint', 'Update notification status'),
  p('communication', 'email-template', 'read', 'endpoint', 'View email templates'),
  p('communication', 'email-template', 'create', 'endpoint', 'Create email templates'),

  // Projects
  p('projects', 'project', 'read', 'endpoint', 'View projects'),
  p('projects', 'project', 'create', 'endpoint', 'Create projects'),
  p('projects', 'project', 'update', 'endpoint', 'Update projects'),
  p('projects', 'project', 'delete', 'endpoint', 'Delete projects'),
  p('projects', 'task', 'read', 'endpoint', 'View tasks'),
  p('projects', 'task', 'create', 'endpoint', 'Create tasks'),
  p('projects', 'task', 'update', 'endpoint', 'Update tasks'),
  p('projects', 'timesheet', 'read', 'endpoint', 'View timesheets'),
  p('projects', 'timesheet', 'create', 'endpoint', 'Create timesheets'),
  p('projects', 'timesheet', 'approve', 'endpoint', 'Approve timesheets'),
  p('projects', 'milestone', 'read', 'endpoint', 'View milestones'),
  p('projects', 'milestone', 'create', 'endpoint', 'Create milestones'),
  p('projects', 'budget', 'read', 'endpoint', 'View project budgets'),
  p('projects', 'budget', 'update', 'endpoint', 'Update project budgets'),
  p('projects', 'risk', 'read', 'endpoint', 'View project risks'),
  p('projects', 'risk', 'create', 'endpoint', 'Create project risks'),
  p('projects', 'portfolio', 'read', 'endpoint', 'View project portfolios'),

  // POS
  p('pos', 'terminal', 'read', 'endpoint', 'View POS terminals'),
  p('pos', 'terminal', 'create', 'endpoint', 'Create POS terminals'),
  p('pos', 'register', 'read', 'endpoint', 'View registers'),
  p('pos', 'register', 'open', 'endpoint', 'Open register session'),
  p('pos', 'register', 'close', 'endpoint', 'Close register session'),
  p('pos', 'receipt', 'read', 'endpoint', 'View receipts'),
  p('pos', 'receipt', 'create', 'endpoint', 'Create POS receipts'),
  p('pos', 'receipt', 'void', 'endpoint', 'Void POS receipts'),
  p('pos', 'shift', 'read', 'endpoint', 'View cashier shifts'),
  p('pos', 'shift', 'manage', 'endpoint', 'Manage cashier shift (cash-in/out, declare)'),

  // Supply Chain
  p('supply-chain', 'shipment', 'read', 'endpoint', 'View shipments'),
  p('supply-chain', 'shipment', 'create', 'endpoint', 'Create shipments'),
  p('supply-chain', 'shipment', 'update', 'endpoint', 'Update shipments'),
  p('supply-chain', 'carrier', 'read', 'endpoint', 'View carriers'),
  p('supply-chain', 'carrier', 'create', 'endpoint', 'Create carriers'),
  p('supply-chain', 'route', 'read', 'endpoint', 'View routes'),
  p('supply-chain', 'forecast', 'read', 'endpoint', 'View demand forecasts'),
  p('supply-chain', 'forecast', 'create', 'endpoint', 'Create demand forecasts'),

  // Manufacturing (extended)
  p('manufacturing', 'production-plan', 'read', 'endpoint', 'View production plans'),
  p('manufacturing', 'production-plan', 'create', 'endpoint', 'Create production plans'),
  p('manufacturing', 'routing', 'read', 'endpoint', 'View manufacturing routings'),
  p('manufacturing', 'routing', 'create', 'endpoint', 'Create manufacturing routings'),
  p('manufacturing', 'equipment', 'read', 'endpoint', 'View manufacturing equipment'),
  p('manufacturing', 'equipment', 'create', 'endpoint', 'Create manufacturing equipment'),
  p('manufacturing', 'eco', 'read', 'endpoint', 'View engineering change orders'),
  p('manufacturing', 'eco', 'create', 'endpoint', 'Create engineering change orders'),

  // Advanced HR
  p('hr', 'leave-policy', 'read', 'endpoint', 'View leave policies'),
  p('hr', 'leave-policy', 'create', 'endpoint', 'Create leave policies'),
  p('hr', 'shift', 'read', 'endpoint', 'View shift schedules'),
  p('hr', 'shift', 'create', 'endpoint', 'Create shift schedules'),
  p('hr', 'appraisal', 'read', 'endpoint', 'View performance appraisals'),
  p('hr', 'appraisal', 'create', 'endpoint', 'Create performance appraisals'),
  p('hr', 'training', 'read', 'endpoint', 'View training and certifications'),
  p('hr', 'training', 'create', 'endpoint', 'Create training events'),

  // Advanced Inventory
  p('inventory', 'serial-number', 'read', 'endpoint', 'View serial numbers'),
  p('inventory', 'serial-number', 'create', 'endpoint', 'Create serial numbers'),
  p('inventory', 'batch', 'read', 'endpoint', 'View batches'),
  p('inventory', 'batch', 'create', 'endpoint', 'Create batches'),
  p('inventory', 'bin-location', 'read', 'endpoint', 'View bin locations'),
  p('inventory', 'bin-location', 'create', 'endpoint', 'Create bin locations'),
  p('inventory', 'cycle-count', 'read', 'endpoint', 'View cycle counts'),
  p('inventory', 'cycle-count', 'create', 'endpoint', 'Create cycle counts'),

  // Workflow Engine — 2-segment legacy codes used by workflow-engine.controller.ts
  { code: 'workflow.create', module: 'workflow', resource: 'general', action: 'create', level: 'endpoint', description: 'Create workflow engine items (legacy coarse permission)' },
  // Workflow Engine — fine-grained resource permissions
  p('workflow', 'workflow', 'read', 'endpoint', 'View workflows'),
  p('workflow', 'workflow', 'create', 'endpoint', 'Create workflows'),
  p('workflow', 'workflow', 'update', 'endpoint', 'Update workflows'),
  p('workflow', 'workflow', 'delete', 'endpoint', 'Delete workflows'),
  p('workflow', 'workflow', 'execute', 'endpoint', 'Execute and simulate workflows'),

  // Notifications
  p('notifications', 'channel', 'read', 'endpoint', 'View notification channels'),
  p('notifications', 'channel', 'update', 'endpoint', 'Manage notification channels'),
  p('notifications', 'preference', 'read', 'endpoint', 'View notification preferences'),
  p('notifications', 'preference', 'update', 'endpoint', 'Update notification preferences'),
  p('notifications', 'digest', 'read', 'endpoint', 'View notification digests'),

  // File Storage / Drive
  p('documents', 'document', 'read', 'endpoint', 'View documents'),
  p('documents', 'document', 'create', 'endpoint', 'Upload documents'),
  p('documents', 'document', 'update', 'endpoint', 'Update document properties'),
  p('documents', 'document', 'delete', 'endpoint', 'Delete documents'),
  p('documents', 'document', 'share', 'endpoint', 'Share documents'),
  p('documents', 'folder', 'read', 'endpoint', 'View folders'),
  p('documents', 'folder', 'create', 'endpoint', 'Create folders'),
  p('documents', 'folder', 'update', 'endpoint', 'Update folders'),
  p('documents', 'folder', 'delete', 'endpoint', 'Delete folders'),
  p('documents', 'template', 'read', 'endpoint', 'View document templates'),
  p('documents', 'template', 'create', 'endpoint', 'Create document templates'),
  p('documents', 'storage-quota', 'read', 'endpoint', 'View storage quotas'),
  p('documents', 'storage-quota', 'manage', 'endpoint', 'Manage storage quotas'),

  // Advanced Reporting
  p('reporting', 'dashboard', 'read', 'endpoint', 'View dashboards'),
  p('reporting', 'dashboard', 'create', 'endpoint', 'Create dashboards'),
  p('reporting', 'widget', 'read', 'endpoint', 'View report widgets'),
  p('reporting', 'widget', 'create', 'endpoint', 'Create report widgets'),
  p('reporting', 'scheduled-report', 'read', 'endpoint', 'View scheduled reports'),
  p('reporting', 'scheduled-report', 'create', 'endpoint', 'Create scheduled reports'),
  p('reporting', 'scheduled-report', 'update', 'endpoint', 'Update scheduled reports'),
  p('reporting', 'saved-view', 'read', 'endpoint', 'View saved report views'),

  // AI — 2-segment codes matching @Permissions('ai.read') etc. in ai.controller.ts
  { code: 'ai.read', module: 'ai', resource: 'general', action: 'read', level: 'endpoint', description: 'View AI module status, config, and chat' },
  { code: 'ai.create', module: 'ai', resource: 'general', action: 'create', level: 'endpoint', description: 'Send AI queries and agent tasks' },
  { code: 'ai.admin.manage', module: 'ai', resource: 'admin', action: 'manage', level: 'endpoint', description: 'Manage global AI settings (kill switch, engine control)' },

  // API Platform
  p('api-platform', 'api-key', 'read', 'endpoint', 'View API keys'),
  p('api-platform', 'api-key', 'create', 'endpoint', 'Create API keys'),
  p('api-platform', 'api-key', 'revoke', 'endpoint', 'Revoke API keys'),
  p('api-platform', 'webhook', 'read', 'endpoint', 'View webhooks'),
  p('api-platform', 'webhook', 'create', 'endpoint', 'Create webhooks'),
  p('api-platform', 'webhook', 'update', 'endpoint', 'Update webhooks'),
  p('api-platform', 'webhook', 'delete', 'endpoint', 'Delete webhooks'),
  p('api-platform', 'integration', 'read', 'endpoint', 'View integrations'),

  // SaaS / Subscription
  p('saas', 'tenant', 'read', 'endpoint', 'View tenants'),
  p('saas', 'tenant', 'create', 'endpoint', 'Create tenants'),
  p('saas', 'subscription', 'read', 'endpoint', 'View tenant subscriptions'),
  p('saas', 'subscription', 'manage', 'endpoint', 'Manage tenant subscriptions and plans'),
  p('saas', 'metering', 'read', 'endpoint', 'View usage metering data'),
  p('saas', 'marketplace', 'read', 'endpoint', 'View marketplace apps'),

  // i18n & Localization
  p('i18n', 'translation', 'read', 'endpoint', 'View translations'),
  p('i18n', 'translation', 'update', 'endpoint', 'Override translations'),

  // PWA / Mobile
  p('pwa', 'sync-queue', 'read', 'endpoint', 'View offline sync queue'),
  p('pwa', 'sync-queue', 'manage', 'endpoint', 'Manage offline sync operations'),

  // Fixed Asset Management (module #35)
  p('fixed-assets', 'category', 'read', 'endpoint', 'View fixed asset categories'),
  p('fixed-assets', 'category', 'create', 'endpoint', 'Create fixed asset categories'),
  p('fixed-assets', 'asset', 'read', 'endpoint', 'View fixed assets'),
  p('fixed-assets', 'asset', 'create', 'endpoint', 'Create fixed assets'),
  p('fixed-assets', 'asset', 'update', 'endpoint', 'Update fixed assets'),
  p('fixed-assets', 'depreciation', 'run', 'endpoint', 'Run depreciation'),
  p('fixed-assets', 'depreciation', 'read', 'endpoint', 'View depreciation schedules'),
  p('fixed-assets', 'maintenance', 'read', 'endpoint', 'View maintenance logs'),
  p('fixed-assets', 'maintenance', 'create', 'endpoint', 'Create maintenance logs'),
  p('fixed-assets', 'transfer', 'read', 'endpoint', 'View asset transfers'),
  p('fixed-assets', 'transfer', 'create', 'endpoint', 'Create asset transfers'),

  // Marketplace (module #34)
  p('marketplace', 'storefront', 'read', 'endpoint', 'Browse the marketplace storefront'),
  p('marketplace', 'vendor', 'read', 'endpoint', 'View marketplace vendors'),
  p('marketplace', 'vendor', 'manage', 'endpoint', 'Manage marketplace vendor profile'),
  p('marketplace', 'bundle', 'read', 'endpoint', 'View app bundles'),
  p('marketplace', 'bundle', 'install', 'endpoint', 'Install app bundles'),
  p('marketplace', 'package', 'read', 'endpoint', 'View app packages'),
  p('marketplace', 'package', 'create', 'endpoint', 'Publish app packages'),

  // Studio / Builder (module #31)
  p('studio', 'form', 'read', 'endpoint', 'View studio forms'),
  p('studio', 'form', 'create', 'endpoint', 'Create studio forms'),
  p('studio', 'page', 'read', 'endpoint', 'View studio pages'),
  p('studio', 'page', 'create', 'endpoint', 'Create studio pages'),
  p('studio', 'workflow', 'read', 'endpoint', 'View studio workflows'),
  p('studio', 'workflow', 'create', 'endpoint', 'Create studio workflows'),
  p('studio', 'dashboard', 'read', 'endpoint', 'View studio dashboards'),
  p('studio', 'dashboard', 'create', 'endpoint', 'Create studio dashboards'),
  p('studio', 'app', 'read', 'endpoint', 'View studio apps'),
  p('studio', 'app', 'create', 'endpoint', 'Create studio apps'),
  p('studio', 'app', 'release', 'endpoint', 'Release app versions'),
  p('studio', 'app', 'install', 'endpoint', 'Install apps from marketplace'),
  p('studio', 'web-collection', 'read', 'endpoint', 'View web collections'),
  p('studio', 'web-collection', 'create', 'endpoint', 'Create web collections'),

  // CRM — contracts (plural resource, matching crm-contracts.controller.ts)
  p('crm', 'contracts', 'read', 'endpoint', 'View contracts'),
  p('crm', 'contracts', 'create', 'endpoint', 'Create contracts'),
  p('crm', 'contracts', 'update', 'endpoint', 'Update contracts'),
  p('crm', 'contracts', 'delete', 'endpoint', 'Delete contracts'),
  p('crm', 'contracts', 'renew', 'endpoint', 'Renew contracts'),

  // Devops / Super Admin
  p('system', 'operations', 'backup', 'endpoint', 'Create/restore system backups (super-admin)'),
  p('system', 'operations', 'read', 'endpoint', 'View system operations dashboard'),
  p('system', 'tenant', 'read', 'endpoint', 'View all tenants (super-admin)'),
  p('system', 'tenant', 'manage', 'endpoint', 'Manage tenants (super-admin)'),
  // ── Auto-registered from permissions-drift check (2026-07-10) ──
  // These codes are actively used by @Permissions(...) decorators in controllers
  // across the codebase but were missing from the registry, which fails the
  // RBAC drift-check test gate. Descriptions are mechanically derived from the
  // code; refine wording opportunistically when touching a given module.
  { code: 'system.tenant.create', module: 'system', resource: 'tenant', action: 'create', level: 'endpoint', description: 'Create Tenant (system)' },
  { code: 'system.tenant.update', module: 'system', resource: 'tenant', action: 'update', level: 'endpoint', description: 'Update Tenant (system)' },
  { code: 'system.superadmin.access', module: 'system', resource: 'superadmin', action: 'access', level: 'endpoint', description: 'Access Superadmin (system)' },
  { code: 'system.analytics.read', module: 'system', resource: 'analytics', action: 'read', level: 'endpoint', description: 'View Analytics (system)' },
  { code: 'system.health.read', module: 'system', resource: 'health', action: 'read', level: 'endpoint', description: 'View Health (system)' },
  { code: 'finance.eliminations.read', module: 'finance', resource: 'eliminations', action: 'read', level: 'endpoint', description: 'View Eliminations (finance)' },
  { code: 'finance.eliminations.manage', module: 'finance', resource: 'eliminations', action: 'manage', level: 'endpoint', description: 'Manage Eliminations (finance)' },
  { code: 'finance.eliminations.run', module: 'finance', resource: 'eliminations', action: 'run', level: 'endpoint', description: 'Run Eliminations (finance)' },
  { code: 'finance.accounting-book.read', module: 'finance', resource: 'accounting-book', action: 'read', level: 'endpoint', description: 'View Accounting Book (finance)' },
  { code: 'finance.accounting-book.create', module: 'finance', resource: 'accounting-book', action: 'create', level: 'endpoint', description: 'Create Accounting Book (finance)' },
  { code: 'finance.payables.read', module: 'finance', resource: 'payables', action: 'read', level: 'endpoint', description: 'View Payables (finance)' },
  { code: 'finance.payables.manage', module: 'finance', resource: 'payables', action: 'manage', level: 'endpoint', description: 'Manage Payables (finance)' },
  { code: 'finance.payables.match', module: 'finance', resource: 'payables', action: 'match', level: 'endpoint', description: 'Reconcile Payables (finance)' },
  { code: 'finance.payables.run', module: 'finance', resource: 'payables', action: 'run', level: 'endpoint', description: 'Run Payables (finance)' },
  { code: 'finance.tax1099.read', module: 'finance', resource: 'tax1099', action: 'read', level: 'endpoint', description: 'View 1099 vendor tax reporting (finance)' },
  { code: 'finance.tax1099.manage', module: 'finance', resource: 'tax1099', action: 'manage', level: 'endpoint', description: 'Manage 1099 vendor tax reporting (finance)' },
  { code: 'finance.tax-nexus.read', module: 'finance', resource: 'tax-nexus', action: 'read', level: 'endpoint', description: 'View economic nexus monitoring & thresholds (finance)' },
  { code: 'finance.tax-nexus.manage', module: 'finance', resource: 'tax-nexus', action: 'manage', level: 'endpoint', description: 'Manage economic nexus thresholds, registrations & recompute monitoring (finance)' },
  { code: 'finance.fpa.read', module: 'finance', resource: 'fpa', action: 'read', level: 'endpoint', description: 'View Fpa (finance)' },
  { code: 'finance.fpa.manage', module: 'finance', resource: 'fpa', action: 'manage', level: 'endpoint', description: 'Manage Fpa (finance)' },
  { code: 'finance.fpa.run', module: 'finance', resource: 'fpa', action: 'run', level: 'endpoint', description: 'Run Fpa (finance)' },
  { code: 'finance.allocations.read', module: 'finance', resource: 'allocations', action: 'read', level: 'endpoint', description: 'View Allocations (finance)' },
  { code: 'finance.allocations.manage', module: 'finance', resource: 'allocations', action: 'manage', level: 'endpoint', description: 'Manage Allocations (finance)' },
  { code: 'finance.allocations.run', module: 'finance', resource: 'allocations', action: 'run', level: 'endpoint', description: 'Run Allocations (finance)' },
  { code: 'finance.treasury.update', module: 'finance', resource: 'treasury', action: 'update', level: 'endpoint', description: 'Update Treasury (finance)' },
  { code: 'finance.payables.create', module: 'finance', resource: 'payables', action: 'create', level: 'endpoint', description: 'Create Payables (finance)' },
  { code: 'finance.payables.update', module: 'finance', resource: 'payables', action: 'update', level: 'endpoint', description: 'Update Payables (finance)' },
  { code: 'finance.payables.delete', module: 'finance', resource: 'payables', action: 'delete', level: 'endpoint', description: 'Delete Payables (finance)' },
  { code: 'finance.receivables.read', module: 'finance', resource: 'receivables', action: 'read', level: 'endpoint', description: 'View Receivables (finance)' },
  { code: 'finance.receivables.create', module: 'finance', resource: 'receivables', action: 'create', level: 'endpoint', description: 'Create Receivables (finance)' },
  { code: 'finance.receivables.update', module: 'finance', resource: 'receivables', action: 'update', level: 'endpoint', description: 'Update Receivables (finance)' },
  { code: 'finance.assets.read', module: 'finance', resource: 'assets', action: 'read', level: 'endpoint', description: 'View Assets (finance)' },
  { code: 'finance.assets.create', module: 'finance', resource: 'assets', action: 'create', level: 'endpoint', description: 'Create Assets (finance)' },
  { code: 'finance.assets.update', module: 'finance', resource: 'assets', action: 'update', level: 'endpoint', description: 'Update Assets (finance)' },
  { code: 'finance.reports.create', module: 'finance', resource: 'reports', action: 'create', level: 'endpoint', description: 'Create Reports (finance)' },
  { code: 'finance.reports.update', module: 'finance', resource: 'reports', action: 'update', level: 'endpoint', description: 'Update Reports (finance)' },
  { code: 'finance.reports.delete', module: 'finance', resource: 'reports', action: 'delete', level: 'endpoint', description: 'Delete Reports (finance)' },
  { code: 'finance.revenue.update', module: 'finance', resource: 'revenue', action: 'update', level: 'endpoint', description: 'Update Revenue (finance)' },
  { code: 'finance.revenue.delete', module: 'finance', resource: 'revenue', action: 'delete', level: 'endpoint', description: 'Delete Revenue (finance)' },
  { code: 'hr.leave.create', module: 'hr', resource: 'leave', action: 'create', level: 'endpoint', description: 'Create Leave (hr)' },
  { code: 'analytics.dashboard.read', module: 'analytics', resource: 'dashboard', action: 'read', level: 'endpoint', description: 'View Dashboard (analytics)' },
  { code: 'analytics.dashboard.create', module: 'analytics', resource: 'dashboard', action: 'create', level: 'endpoint', description: 'Create Dashboard (analytics)' },
  { code: 'analytics.report.read', module: 'analytics', resource: 'report', action: 'read', level: 'endpoint', description: 'View Report (analytics)' },
  { code: 'analytics.report.create', module: 'analytics', resource: 'report', action: 'create', level: 'endpoint', description: 'Create Report (analytics)' },
  { code: 'analytics.kpi.read', module: 'analytics', resource: 'kpi', action: 'read', level: 'endpoint', description: 'View Kpi (analytics)' },
  { code: 'admin.api-keys.read', module: 'admin', resource: 'api-keys', action: 'read', level: 'endpoint', description: 'View Api Keys (admin)' },
  { code: 'admin.api-keys.create', module: 'admin', resource: 'api-keys', action: 'create', level: 'endpoint', description: 'Create Api Keys (admin)' },
  { code: 'admin.api-keys.delete', module: 'admin', resource: 'api-keys', action: 'delete', level: 'endpoint', description: 'Delete Api Keys (admin)' },
  { code: 'admin.webhooks.read', module: 'admin', resource: 'webhooks', action: 'read', level: 'endpoint', description: 'View Webhooks (admin)' },
  { code: 'admin.webhooks.create', module: 'admin', resource: 'webhooks', action: 'create', level: 'endpoint', description: 'Create Webhooks (admin)' },
  { code: 'admin.webhooks.delete', module: 'admin', resource: 'webhooks', action: 'delete', level: 'endpoint', description: 'Delete Webhooks (admin)' },
  { code: 'auth.create', module: 'auth', resource: 'general', action: 'create', level: 'endpoint', description: 'Create Auth module (legacy coarse permission)' },
  { code: 'auth.read', module: 'auth', resource: 'general', action: 'read', level: 'endpoint', description: 'View Auth module (legacy coarse permission)' },
  { code: 'auth.update', module: 'auth', resource: 'general', action: 'update', level: 'endpoint', description: 'Update Auth module (legacy coarse permission)' },
  { code: 'builder.read', module: 'builder', resource: 'general', action: 'read', level: 'endpoint', description: 'View Builder module (legacy coarse permission)' },
  { code: 'builder.form.read', module: 'builder', resource: 'form', action: 'read', level: 'endpoint', description: 'View Form (builder)' },
  { code: 'builder.form.create', module: 'builder', resource: 'form', action: 'create', level: 'endpoint', description: 'Create Form (builder)' },
  { code: 'builder.form.update', module: 'builder', resource: 'form', action: 'update', level: 'endpoint', description: 'Update Form (builder)' },
  { code: 'builder.form.delete', module: 'builder', resource: 'form', action: 'delete', level: 'endpoint', description: 'Delete Form (builder)' },
  { code: 'builder.workflow.read', module: 'builder', resource: 'workflow', action: 'read', level: 'endpoint', description: 'View Workflow (builder)' },
  { code: 'builder.workflow.create', module: 'builder', resource: 'workflow', action: 'create', level: 'endpoint', description: 'Create Workflow (builder)' },
  { code: 'builder.workflow.update', module: 'builder', resource: 'workflow', action: 'update', level: 'endpoint', description: 'Update Workflow (builder)' },
  { code: 'builder.workflow.delete', module: 'builder', resource: 'workflow', action: 'delete', level: 'endpoint', description: 'Delete Workflow (builder)' },
  { code: 'builder.dashboard.read', module: 'builder', resource: 'dashboard', action: 'read', level: 'endpoint', description: 'View Dashboard (builder)' },
  { code: 'builder.dashboard.create', module: 'builder', resource: 'dashboard', action: 'create', level: 'endpoint', description: 'Create Dashboard (builder)' },
  { code: 'builder.dashboard.update', module: 'builder', resource: 'dashboard', action: 'update', level: 'endpoint', description: 'Update Dashboard (builder)' },
  { code: 'builder.dashboard.delete', module: 'builder', resource: 'dashboard', action: 'delete', level: 'endpoint', description: 'Delete Dashboard (builder)' },
  { code: 'builder.module.read', module: 'builder', resource: 'module', action: 'read', level: 'endpoint', description: 'View Module (builder)' },
  { code: 'builder.module.create', module: 'builder', resource: 'module', action: 'create', level: 'endpoint', description: 'Create Module (builder)' },
  { code: 'builder.module.update', module: 'builder', resource: 'module', action: 'update', level: 'endpoint', description: 'Update Module (builder)' },
  { code: 'builder.module.delete', module: 'builder', resource: 'module', action: 'delete', level: 'endpoint', description: 'Delete Module (builder)' },
  { code: 'builder.automation.read', module: 'builder', resource: 'automation', action: 'read', level: 'endpoint', description: 'View Automation (builder)' },
  { code: 'builder.automation.create', module: 'builder', resource: 'automation', action: 'create', level: 'endpoint', description: 'Create Automation (builder)' },
  { code: 'builder.automation.update', module: 'builder', resource: 'automation', action: 'update', level: 'endpoint', description: 'Update Automation (builder)' },
  { code: 'builder.automation.delete', module: 'builder', resource: 'automation', action: 'delete', level: 'endpoint', description: 'Delete Automation (builder)' },
  { code: 'builder.import.read', module: 'builder', resource: 'import', action: 'read', level: 'endpoint', description: 'View Import (builder)' },
  { code: 'builder.import.create', module: 'builder', resource: 'import', action: 'create', level: 'endpoint', description: 'Create Import (builder)' },
  { code: 'builder.web.read', module: 'builder', resource: 'web', action: 'read', level: 'endpoint', description: 'View Web (builder)' },
  { code: 'builder.web.create', module: 'builder', resource: 'web', action: 'create', level: 'endpoint', description: 'Create Web (builder)' },
  { code: 'builder.web.update', module: 'builder', resource: 'web', action: 'update', level: 'endpoint', description: 'Update Web (builder)' },
  { code: 'builder.web.delete', module: 'builder', resource: 'web', action: 'delete', level: 'endpoint', description: 'Delete Web (builder)' },
  { code: 'builder.blog.read', module: 'builder', resource: 'blog', action: 'read', level: 'endpoint', description: 'View Blog (builder)' },
  { code: 'builder.blog.create', module: 'builder', resource: 'blog', action: 'create', level: 'endpoint', description: 'Create Blog (builder)' },
  { code: 'builder.blog.update', module: 'builder', resource: 'blog', action: 'update', level: 'endpoint', description: 'Update Blog (builder)' },
  { code: 'builder.blog.delete', module: 'builder', resource: 'blog', action: 'delete', level: 'endpoint', description: 'Delete Blog (builder)' },
  { code: 'builder.schema.read', module: 'builder', resource: 'schema', action: 'read', level: 'endpoint', description: 'View Schema (builder)' },
  { code: 'builder.schema.create', module: 'builder', resource: 'schema', action: 'create', level: 'endpoint', description: 'Create Schema (builder)' },
  { code: 'builder.schema.update', module: 'builder', resource: 'schema', action: 'update', level: 'endpoint', description: 'Update Schema (builder)' },
  { code: 'builder.schema.delete', module: 'builder', resource: 'schema', action: 'delete', level: 'endpoint', description: 'Delete Schema (builder)' },
  { code: 'builder.page.read', module: 'builder', resource: 'page', action: 'read', level: 'endpoint', description: 'View Page (builder)' },
  { code: 'builder.page.create', module: 'builder', resource: 'page', action: 'create', level: 'endpoint', description: 'Create Page (builder)' },
  { code: 'builder.page.update', module: 'builder', resource: 'page', action: 'update', level: 'endpoint', description: 'Update Page (builder)' },
  { code: 'builder.page.delete', module: 'builder', resource: 'page', action: 'delete', level: 'endpoint', description: 'Delete Page (builder)' },
  { code: 'builder.record.read', module: 'builder', resource: 'record', action: 'read', level: 'endpoint', description: 'View Record (builder)' },
  { code: 'builder.record.create', module: 'builder', resource: 'record', action: 'create', level: 'endpoint', description: 'Create Record (builder)' },
  { code: 'builder.record.update', module: 'builder', resource: 'record', action: 'update', level: 'endpoint', description: 'Update Record (builder)' },
  { code: 'builder.record.delete', module: 'builder', resource: 'record', action: 'delete', level: 'endpoint', description: 'Delete Record (builder)' },
  { code: 'builder.update', module: 'builder', resource: 'general', action: 'update', level: 'endpoint', description: 'Update Builder module (legacy coarse permission)' },
  { code: 'builder.create', module: 'builder', resource: 'general', action: 'create', level: 'endpoint', description: 'Create Builder module (legacy coarse permission)' },
  { code: 'builder.delete', module: 'builder', resource: 'general', action: 'delete', level: 'endpoint', description: 'Delete Builder module (legacy coarse permission)' },
  { code: 'crm.duplicate-rules.read', module: 'crm', resource: 'duplicate-rules', action: 'read', level: 'endpoint', description: 'View Duplicate Rules (crm)' },
  { code: 'crm.duplicate-rules.create', module: 'crm', resource: 'duplicate-rules', action: 'create', level: 'endpoint', description: 'Create Duplicate Rules (crm)' },
  { code: 'crm.duplicate-rules.update', module: 'crm', resource: 'duplicate-rules', action: 'update', level: 'endpoint', description: 'Update Duplicate Rules (crm)' },
  { code: 'crm.duplicate-rules.delete', module: 'crm', resource: 'duplicate-rules', action: 'delete', level: 'endpoint', description: 'Delete Duplicate Rules (crm)' },
  { code: 'crm.duplicates.scan', module: 'crm', resource: 'duplicates', action: 'scan', level: 'endpoint', description: 'Scan Duplicates (crm)' },
  { code: 'crm.duplicates.merge', module: 'crm', resource: 'duplicates', action: 'merge', level: 'endpoint', description: 'Merge Duplicates (crm)' },
  { code: 'crm.lead-scoring.read', module: 'crm', resource: 'lead-scoring', action: 'read', level: 'endpoint', description: 'View Lead Scoring (crm)' },
  { code: 'crm.lead-scoring.create', module: 'crm', resource: 'lead-scoring', action: 'create', level: 'endpoint', description: 'Create Lead Scoring (crm)' },
  { code: 'crm.report.read', module: 'crm', resource: 'report', action: 'read', level: 'endpoint', description: 'View Report (crm)' },
  { code: 'crm.lead-scoring.update', module: 'crm', resource: 'lead-scoring', action: 'update', level: 'endpoint', description: 'Update Lead Scoring (crm)' },
  { code: 'crm.lead-scoring.delete', module: 'crm', resource: 'lead-scoring', action: 'delete', level: 'endpoint', description: 'Delete Lead Scoring (crm)' },
  { code: 'crm.lead-scoring.recalculate', module: 'crm', resource: 'lead-scoring', action: 'recalculate', level: 'endpoint', description: 'Recalculate Lead Scoring (crm)' },
  { code: 'crm.pipelines.read', module: 'crm', resource: 'pipelines', action: 'read', level: 'endpoint', description: 'View Pipelines (crm)' },
  { code: 'crm.pipelines.create', module: 'crm', resource: 'pipelines', action: 'create', level: 'endpoint', description: 'Create Pipelines (crm)' },
  { code: 'crm.pipelines.update', module: 'crm', resource: 'pipelines', action: 'update', level: 'endpoint', description: 'Update Pipelines (crm)' },
  { code: 'crm.pipelines.delete', module: 'crm', resource: 'pipelines', action: 'delete', level: 'endpoint', description: 'Delete Pipelines (crm)' },
  { code: 'crm.segments.read', module: 'crm', resource: 'segments', action: 'read', level: 'endpoint', description: 'View Segments (crm)' },
  { code: 'crm.segments.create', module: 'crm', resource: 'segments', action: 'create', level: 'endpoint', description: 'Create Segments (crm)' },
  { code: 'crm.segments.update', module: 'crm', resource: 'segments', action: 'update', level: 'endpoint', description: 'Update Segments (crm)' },
  { code: 'crm.segments.delete', module: 'crm', resource: 'segments', action: 'delete', level: 'endpoint', description: 'Delete Segments (crm)' },
  { code: 'crm.sla-policies.read', module: 'crm', resource: 'sla-policies', action: 'read', level: 'endpoint', description: 'View Sla Policies (crm)' },
  { code: 'crm.sla-policies.create', module: 'crm', resource: 'sla-policies', action: 'create', level: 'endpoint', description: 'Create Sla Policies (crm)' },
  { code: 'crm.sla-policies.update', module: 'crm', resource: 'sla-policies', action: 'update', level: 'endpoint', description: 'Update Sla Policies (crm)' },
  { code: 'crm.sla-policies.delete', module: 'crm', resource: 'sla-policies', action: 'delete', level: 'endpoint', description: 'Delete Sla Policies (crm)' },
  { code: 'crm.opportunity.delete', module: 'crm', resource: 'opportunity', action: 'delete', level: 'endpoint', description: 'Delete Opportunity (crm)' },
  { code: 'crm.activity.update', module: 'crm', resource: 'activity', action: 'update', level: 'endpoint', description: 'Update Activity (crm)' },
  { code: 'crm.settings.read', module: 'crm', resource: 'settings', action: 'read', level: 'endpoint', description: 'View Settings (crm)' },
  { code: 'crm.settings.create', module: 'crm', resource: 'settings', action: 'create', level: 'endpoint', description: 'Create Settings (crm)' },
  { code: 'crm.settings.update', module: 'crm', resource: 'settings', action: 'update', level: 'endpoint', description: 'Update Settings (crm)' },
  { code: 'crm.settings.delete', module: 'crm', resource: 'settings', action: 'delete', level: 'endpoint', description: 'Delete Settings (crm)' },
  { code: 'crm.product.read', module: 'crm', resource: 'product', action: 'read', level: 'endpoint', description: 'View Product (crm)' },
  { code: 'crm.product.create', module: 'crm', resource: 'product', action: 'create', level: 'endpoint', description: 'Create Product (crm)' },
  { code: 'crm.product.update', module: 'crm', resource: 'product', action: 'update', level: 'endpoint', description: 'Update Product (crm)' },
  { code: 'crm.product.delete', module: 'crm', resource: 'product', action: 'delete', level: 'endpoint', description: 'Delete Product (crm)' },
  { code: 'crm.report.create', module: 'crm', resource: 'report', action: 'create', level: 'endpoint', description: 'Create Report (crm)' },
  { code: 'crm.report.delete', module: 'crm', resource: 'report', action: 'delete', level: 'endpoint', description: 'Delete Report (crm)' },
  { code: 'crm.create', module: 'crm', resource: 'general', action: 'create', level: 'endpoint', description: 'Create Crm module (legacy coarse permission)' },
  { code: 'crm.read', module: 'crm', resource: 'general', action: 'read', level: 'endpoint', description: 'View Crm module (legacy coarse permission)' },
  { code: 'crm.report.update', module: 'crm', resource: 'report', action: 'update', level: 'endpoint', description: 'Update Report (crm)' },
  { code: 'admin.devops.read', module: 'admin', resource: 'devops', action: 'read', level: 'endpoint', description: 'View Devops (admin)' },
  { code: 'finance.leases.read', module: 'finance', resource: 'leases', action: 'read', level: 'endpoint', description: 'View Leases (finance)' },
  { code: 'finance.leases.post', module: 'finance', resource: 'leases', action: 'post', level: 'endpoint', description: 'Post Leases (finance)' },
  { code: 'finance.leases.create', module: 'finance', resource: 'leases', action: 'create', level: 'endpoint', description: 'Create Leases (finance)' },
  { code: 'finance.leases.update', module: 'finance', resource: 'leases', action: 'update', level: 'endpoint', description: 'Update Leases (finance)' },
  { code: 'finance.leases.delete', module: 'finance', resource: 'leases', action: 'delete', level: 'endpoint', description: 'Delete Leases (finance)' },
  { code: 'assets.category.manage', module: 'assets', resource: 'category', action: 'manage', level: 'endpoint', description: 'Manage Category (assets)' },
  { code: 'assets.asset.read', module: 'assets', resource: 'asset', action: 'read', level: 'endpoint', description: 'View Asset (assets)' },
  { code: 'assets.asset.create', module: 'assets', resource: 'asset', action: 'create', level: 'endpoint', description: 'Create Asset (assets)' },
  { code: 'assets.asset.update', module: 'assets', resource: 'asset', action: 'update', level: 'endpoint', description: 'Update Asset (assets)' },
  { code: 'assets.transfer.manage', module: 'assets', resource: 'transfer', action: 'manage', level: 'endpoint', description: 'Manage Transfer (assets)' },
  { code: 'assets.maintenance.manage', module: 'assets', resource: 'maintenance', action: 'manage', level: 'endpoint', description: 'Manage Maintenance (assets)' },
  { code: 'assets.depreciation.post', module: 'assets', resource: 'depreciation', action: 'post', level: 'endpoint', description: 'Post Depreciation (assets)' },
  { code: 'inventory.warehouse.update', module: 'inventory', resource: 'warehouse', action: 'update', level: 'endpoint', description: 'Update Warehouse (inventory)' },
  { code: 'inventory.warehouse.delete', module: 'inventory', resource: 'warehouse', action: 'delete', level: 'endpoint', description: 'Delete Warehouse (inventory)' },
  { code: 'inventory.stock.create', module: 'inventory', resource: 'stock', action: 'create', level: 'endpoint', description: 'Create Stock (inventory)' },
  { code: 'inventory.stock.update', module: 'inventory', resource: 'stock', action: 'update', level: 'endpoint', description: 'Update Stock (inventory)' },
  { code: 'inventory.stock.delete', module: 'inventory', resource: 'stock', action: 'delete', level: 'endpoint', description: 'Delete Stock (inventory)' },
  { code: 'inventory.demand_forecast.read', module: 'inventory', resource: 'demand_forecast', action: 'read', level: 'endpoint', description: 'View Demand Forecast (inventory)' },
  { code: 'inventory.demand_forecast.create', module: 'inventory', resource: 'demand_forecast', action: 'create', level: 'endpoint', description: 'Create Demand Forecast (inventory)' },
  { code: 'inventory.demand_forecast.update', module: 'inventory', resource: 'demand_forecast', action: 'update', level: 'endpoint', description: 'Update Demand Forecast (inventory)' },
  { code: 'inventory.demand_forecast.delete', module: 'inventory', resource: 'demand_forecast', action: 'delete', level: 'endpoint', description: 'Delete Demand Forecast (inventory)' },
  { code: 'inventory.demand_forecast.generate', module: 'inventory', resource: 'demand_forecast', action: 'generate', level: 'endpoint', description: 'Generate Demand Forecast run (inventory)' },
  { code: 'inventory.reorder_suggestion.read', module: 'inventory', resource: 'reorder_suggestion', action: 'read', level: 'endpoint', description: 'View Reorder Suggestions (inventory)' },
  { code: 'inventory.reorder_suggestion.update', module: 'inventory', resource: 'reorder_suggestion', action: 'update', level: 'endpoint', description: 'Accept/Dismiss Reorder Suggestion (inventory)' },
  { code: 'inventory.rtv.read', module: 'inventory', resource: 'rtv', action: 'read', level: 'endpoint', description: 'View Returns-to-Vendor (RTV) data (inventory)' },
  { code: 'inventory.rtv.create', module: 'inventory', resource: 'rtv', action: 'create', level: 'endpoint', description: 'Create RMA requests and return shipments (inventory)' },
  { code: 'inventory.rtv.update', module: 'inventory', resource: 'rtv', action: 'update', level: 'endpoint', description: 'Advance RMA/shipment lifecycle stages (inventory)' },
  { code: 'inventory.rtv.manage', module: 'inventory', resource: 'rtv', action: 'manage', level: 'endpoint', description: 'Manage RTV reason codes configuration (inventory)' },
  { code: 'inventory.labor.read', module: 'inventory', resource: 'labor', action: 'read', level: 'endpoint', description: 'View labor standards and task logs (inventory)' },
  { code: 'inventory.labor.create', module: 'inventory', resource: 'labor', action: 'create', level: 'endpoint', description: 'Log worker tasks and manage labor standards (inventory)' },
  { code: 'inventory.labor.manage', module: 'inventory', resource: 'labor', action: 'manage', level: 'endpoint', description: 'Manage shift templates and labor configuration (inventory)' },
  { code: 'inventory.supplier_quality.read', module: 'inventory', resource: 'supplier_quality', action: 'read', level: 'endpoint', description: 'View supplier scorecards and NCRs (inventory)' },
  { code: 'inventory.supplier_quality.create', module: 'inventory', resource: 'supplier_quality', action: 'create', level: 'endpoint', description: 'Raise NCRs and CARs, create scorecards (inventory)' },
  { code: 'inventory.supplier_quality.manage', module: 'inventory', resource: 'supplier_quality', action: 'manage', level: 'endpoint', description: 'Close NCRs and accept/reject CARs (inventory)' },
  { code: 'inventory.automation.read', module: 'inventory', resource: 'automation', action: 'read', level: 'endpoint', description: 'View automation rules and inventory holds (inventory)' },
  { code: 'inventory.automation.create', module: 'inventory', resource: 'automation', action: 'create', level: 'endpoint', description: 'Create replenishment rules and holds (inventory)' },
  { code: 'inventory.automation.manage', module: 'inventory', resource: 'automation', action: 'manage', level: 'endpoint', description: 'Evaluate rules, release/cancel holds (inventory)' },
  { code: 'inventory.analytics.read', module: 'inventory', resource: 'analytics', action: 'read', level: 'endpoint', description: 'View inventory analytics dashboards and reports (inventory)' },
  { code: 'inventory.hazmat.manage', module: 'inventory', resource: 'hazmat', action: 'manage', level: 'endpoint', description: 'Manage Hazmat (hazmat - inventory)' },
  { code: 'inventory.hazmat.read', module: 'inventory', resource: 'hazmat', action: 'read', level: 'endpoint', description: 'View Hazmat (hazmat - inventory)' },
  { code: 'inventory.warehouse_ops.manage', module: 'inventory', resource: 'warehouse_ops', action: 'manage', level: 'endpoint', description: 'Manage Warehouse Ops (warehouse-ops - inventory)' },
  { code: 'inventory.warehouse_ops.read', module: 'inventory', resource: 'warehouse_ops', action: 'read', level: 'endpoint', description: 'View Warehouse Ops (warehouse-ops - inventory)' },
  { code: 'inventory.quality_compliance.manage', module: 'inventory', resource: 'quality_compliance', action: 'manage', level: 'endpoint', description: 'Manage Quality Compliance (quality-compliance - inventory)' },
  { code: 'inventory.quality_compliance.read', module: 'inventory', resource: 'quality_compliance', action: 'read', level: 'endpoint', description: 'View Quality Compliance (quality-compliance - inventory)' },
  { code: 'inventory.lot_serial.manage', module: 'inventory', resource: 'lot_serial', action: 'manage', level: 'endpoint', description: 'Manage Lot Serial (lot-serial-tracking - inventory)' },
  { code: 'inventory.lot_serial.read', module: 'inventory', resource: 'lot_serial', action: 'read', level: 'endpoint', description: 'View Lot Serial (lot-serial-tracking - inventory)' },
  { code: 'inventory.demand_forecast.manage', module: 'inventory', resource: 'demand_forecast', action: 'manage', level: 'endpoint', description: 'Manage Demand Forecast (demand-forecasting - inventory)' },
  { code: 'inventory.yard_management.manage', module: 'inventory', resource: 'yard_management', action: 'manage', level: 'endpoint', description: 'Manage Yard Management (yard-management - inventory)' },
  { code: 'inventory.yard_management.read', module: 'inventory', resource: 'yard_management', action: 'read', level: 'endpoint', description: 'View Yard Management (yard-management - inventory)' },
  { code: 'inventory.container_pallet.read', module: 'inventory', resource: 'container_pallet', action: 'read', level: 'endpoint', description: 'View Container Pallet (container-pallet - inventory)' },
  { code: 'inventory.container_pallet.manage', module: 'inventory', resource: 'container_pallet', action: 'manage', level: 'endpoint', description: 'Manage Container Pallet (container-pallet - inventory)' },
  { code: 'inventory.logistics.manage', module: 'inventory', resource: 'logistics', action: 'manage', level: 'endpoint', description: 'Manage Logistics (inventory-logistics - inventory)' },
  { code: 'inventory.logistics.read', module: 'inventory', resource: 'logistics', action: 'read', level: 'endpoint', description: 'View Logistics (inventory-logistics - inventory)' },
  { code: 'inventory.catch_weight_recall.read', module: 'inventory', resource: 'catch_weight_recall', action: 'read', level: 'endpoint', description: 'View Catch Weight Recall (catch-weight-recall - inventory)' },
  { code: 'inventory.catch_weight_recall.manage', module: 'inventory', resource: 'catch_weight_recall', action: 'manage', level: 'endpoint', description: 'Manage Catch Weight Recall (catch-weight-recall - inventory)' },
  { code: 'inventory.asl.manage', module: 'inventory', resource: 'asl', action: 'manage', level: 'endpoint', description: 'Manage Asl (asl - inventory)' },
  { code: 'inventory.asl.read', module: 'inventory', resource: 'asl', action: 'read', level: 'endpoint', description: 'View Asl (asl - inventory)' },
  { code: 'inventory.stock_valuation.read', module: 'inventory', resource: 'stock_valuation', action: 'read', level: 'endpoint', description: 'View Stock Valuation (stock-valuation - inventory)' },
  { code: 'inventory.stock_valuation.manage', module: 'inventory', resource: 'stock_valuation', action: 'manage', level: 'endpoint', description: 'Manage Stock Valuation (stock-valuation - inventory)' },
  { code: 'inventory.packaging_gs1.read', module: 'inventory', resource: 'packaging_gs1', action: 'read', level: 'endpoint', description: 'View Packaging Gs1 (packaging-gs1 - inventory)' },
  { code: 'inventory.packaging_gs1.manage', module: 'inventory', resource: 'packaging_gs1', action: 'manage', level: 'endpoint', description: 'Manage Packaging Gs1 (packaging-gs1 - inventory)' },
  { code: 'inventory.stock_take.read', module: 'inventory', resource: 'stock_take', action: 'read', level: 'endpoint', description: 'View Stock Take (stock-take - inventory)' },
  { code: 'inventory.stock_take.manage', module: 'inventory', resource: 'stock_take', action: 'manage', level: 'endpoint', description: 'Manage Stock Take (stock-take - inventory)' },
  { code: 'inventory.landed_cost.manage', module: 'inventory', resource: 'landed_cost', action: 'manage', level: 'endpoint', description: 'Manage Landed Cost (landed-cost - inventory)' },
  { code: 'inventory.landed_cost.read', module: 'inventory', resource: 'landed_cost', action: 'read', level: 'endpoint', description: 'View Landed Cost (landed-cost - inventory)' },
  { code: 'inventory.cold_chain_writeoff.read', module: 'inventory', resource: 'cold_chain_writeoff', action: 'read', level: 'endpoint', description: 'View Cold Chain Writeoff (cold-chain-writeoff - inventory)' },
  { code: 'inventory.cold_chain_writeoff.manage', module: 'inventory', resource: 'cold_chain_writeoff', action: 'manage', level: 'endpoint', description: 'Manage Cold Chain Writeoff (cold-chain-writeoff - inventory)' },
  { code: 'inventory.transfer_orders.manage', module: 'inventory', resource: 'transfer_orders', action: 'manage', level: 'endpoint', description: 'Manage Transfer Orders (transfer-orders - inventory)' },
  { code: 'inventory.transfer_orders.read', module: 'inventory', resource: 'transfer_orders', action: 'read', level: 'endpoint', description: 'View Transfer Orders (transfer-orders - inventory)' },
  { code: 'inventory.velocity_abc_xyz.manage', module: 'inventory', resource: 'velocity_abc_xyz', action: 'manage', level: 'endpoint', description: 'Manage Velocity Abc Xyz (velocity-abc-xyz - inventory)' },
  { code: 'inventory.velocity_abc_xyz.read', module: 'inventory', resource: 'velocity_abc_xyz', action: 'read', level: 'endpoint', description: 'View Velocity Abc Xyz (velocity-abc-xyz - inventory)' },
  { code: 'inventory.customer_returns.read', module: 'inventory', resource: 'customer_returns', action: 'read', level: 'endpoint', description: 'View Customer Returns (customer-returns - inventory)' },
  { code: 'inventory.customer_returns.manage', module: 'inventory', resource: 'customer_returns', action: 'manage', level: 'endpoint', description: 'Manage Customer Returns (customer-returns - inventory)' },
  { code: 'inventory.lot_expiry.manage', module: 'inventory', resource: 'lot_expiry', action: 'manage', level: 'endpoint', description: 'Manage Lot Expiry (lot-expiry - inventory)' },
  { code: 'inventory.lot_expiry.read', module: 'inventory', resource: 'lot_expiry', action: 'read', level: 'endpoint', description: 'View Lot Expiry (lot-expiry - inventory)' },
  { code: 'inventory.vmi.read', module: 'inventory', resource: 'vmi', action: 'read', level: 'endpoint', description: 'View Vmi (vmi - inventory)' },
  { code: 'inventory.vmi.manage', module: 'inventory', resource: 'vmi', action: 'manage', level: 'endpoint', description: 'Manage Vmi (vmi - inventory)' },
  { code: 'inventory.freight_claims.manage', module: 'inventory', resource: 'freight_claims', action: 'manage', level: 'endpoint', description: 'Manage Freight Claims (freight-claims - inventory)' },
  { code: 'inventory.freight_claims.read', module: 'inventory', resource: 'freight_claims', action: 'read', level: 'endpoint', description: 'View Freight Claims (freight-claims - inventory)' },
  { code: 'inventory.minmax_replen.manage', module: 'inventory', resource: 'minmax_replen', action: 'manage', level: 'endpoint', description: 'Manage Minmax Replen (minmax-replen - inventory)' },
  { code: 'inventory.minmax_replen.read', module: 'inventory', resource: 'minmax_replen', action: 'read', level: 'endpoint', description: 'View Minmax Replen (minmax-replen - inventory)' },
  { code: 'inventory.costing_methods.manage', module: 'inventory', resource: 'costing_methods', action: 'manage', level: 'endpoint', description: 'Manage Costing Methods (costing-methods - inventory)' },
  { code: 'inventory.costing_methods.read', module: 'inventory', resource: 'costing_methods', action: 'read', level: 'endpoint', description: 'View Costing Methods (costing-methods - inventory)' },
  { code: 'localization.read', module: 'localization', resource: 'general', action: 'read', level: 'endpoint', description: 'View Localization module (legacy coarse permission)' },
  { code: 'manufacturing.work-order.update', module: 'manufacturing', resource: 'work-order', action: 'update', level: 'endpoint', description: 'Update Work Order (manufacturing)' },
  { code: 'manufacturing.bom.update', module: 'manufacturing', resource: 'bom', action: 'update', level: 'endpoint', description: 'Update Bom (manufacturing)' },
  { code: 'manufacturing.create', module: 'manufacturing', resource: 'general', action: 'create', level: 'endpoint', description: 'Create Manufacturing module (legacy coarse permission)' },
  { code: 'manufacturing.read', module: 'manufacturing', resource: 'general', action: 'read', level: 'endpoint', description: 'View Manufacturing module (legacy coarse permission)' },
  { code: 'marketplace.read', module: 'marketplace', resource: 'general', action: 'read', level: 'endpoint', description: 'View Marketplace module (legacy coarse permission)' },
  { code: 'marketplace.create', module: 'marketplace', resource: 'general', action: 'create', level: 'endpoint', description: 'Create Marketplace module (legacy coarse permission)' },
  { code: 'pos.register.create', module: 'pos', resource: 'register', action: 'create', level: 'endpoint', description: 'Create Register (pos)' },
  { code: 'pos.shift.create', module: 'pos', resource: 'shift', action: 'create', level: 'endpoint', description: 'Create Shift (pos)' },
  { code: 'pos.cash-entry.read', module: 'pos', resource: 'cash-entry', action: 'read', level: 'endpoint', description: 'View Cash Entry (pos)' },
  { code: 'pos.cash-entry.create', module: 'pos', resource: 'cash-entry', action: 'create', level: 'endpoint', description: 'Create Cash Entry (pos)' },
  { code: 'pos.order.create', module: 'pos', resource: 'order', action: 'create', level: 'endpoint', description: 'Create Order (pos)' },
  { code: 'pos.order.read', module: 'pos', resource: 'order', action: 'read', level: 'endpoint', description: 'View Order (pos)' },
  { code: 'pos.product.search', module: 'pos', resource: 'product', action: 'search', level: 'endpoint', description: 'Search Product (pos)' },
  { code: 'pos.discount.create', module: 'pos', resource: 'discount', action: 'create', level: 'endpoint', description: 'Create Discount (pos)' },
  { code: 'pos.discount.read', module: 'pos', resource: 'discount', action: 'read', level: 'endpoint', description: 'View Discount (pos)' },
  { code: 'pos.coupon.validate', module: 'pos', resource: 'coupon', action: 'validate', level: 'endpoint', description: 'Validate Coupon (pos)' },
  { code: 'pos.coupon.create', module: 'pos', resource: 'coupon', action: 'create', level: 'endpoint', description: 'Create Coupon (pos)' },
  { code: 'pos.coupon.read', module: 'pos', resource: 'coupon', action: 'read', level: 'endpoint', description: 'View Coupon (pos)' },
  { code: 'pos.tax-profile.create', module: 'pos', resource: 'tax-profile', action: 'create', level: 'endpoint', description: 'Create Tax Profile (pos)' },
  { code: 'pos.tax-profile.read', module: 'pos', resource: 'tax-profile', action: 'read', level: 'endpoint', description: 'View Tax Profile (pos)' },
  { code: 'pos.customer.read', module: 'pos', resource: 'customer', action: 'read', level: 'endpoint', description: 'View Customer (pos)' },
  { code: 'pos.customer.create', module: 'pos', resource: 'customer', action: 'create', level: 'endpoint', description: 'Create Customer (pos)' },
  { code: 'pos.loyalty.create', module: 'pos', resource: 'loyalty', action: 'create', level: 'endpoint', description: 'Create Loyalty (pos)' },
  { code: 'pos.loyalty.read', module: 'pos', resource: 'loyalty', action: 'read', level: 'endpoint', description: 'View Loyalty (pos)' },
  { code: 'pos.loyalty.redeem', module: 'pos', resource: 'loyalty', action: 'redeem', level: 'endpoint', description: 'Redeem Loyalty (pos)' },
  { code: 'pos.gift-card.create', module: 'pos', resource: 'gift-card', action: 'create', level: 'endpoint', description: 'Create Gift Card (pos)' },
  { code: 'pos.gift-card.read', module: 'pos', resource: 'gift-card', action: 'read', level: 'endpoint', description: 'View Gift Card (pos)' },
  { code: 'pos.store-credit.read', module: 'pos', resource: 'store-credit', action: 'read', level: 'endpoint', description: 'View Store Credit (pos)' },
  { code: 'pos.return.create', module: 'pos', resource: 'return', action: 'create', level: 'endpoint', description: 'Create Return (pos)' },
  { code: 'pos.return.read', module: 'pos', resource: 'return', action: 'read', level: 'endpoint', description: 'View Return (pos)' },
  { code: 'pos.held-order.create', module: 'pos', resource: 'held-order', action: 'create', level: 'endpoint', description: 'Create Held Order (pos)' },
  { code: 'pos.held-order.read', module: 'pos', resource: 'held-order', action: 'read', level: 'endpoint', description: 'View Held Order (pos)' },
  { code: 'pos.price-list.create', module: 'pos', resource: 'price-list', action: 'create', level: 'endpoint', description: 'Create Price List (pos)' },
  { code: 'pos.price-list.read', module: 'pos', resource: 'price-list', action: 'read', level: 'endpoint', description: 'View Price List (pos)' },
  { code: 'pos.promotion.create', module: 'pos', resource: 'promotion', action: 'create', level: 'endpoint', description: 'Create Promotion (pos)' },
  { code: 'pos.promotion.read', module: 'pos', resource: 'promotion', action: 'read', level: 'endpoint', description: 'View Promotion (pos)' },
  { code: 'pos.open-tab.create', module: 'pos', resource: 'open-tab', action: 'create', level: 'endpoint', description: 'Create Open Tab (pos)' },
  { code: 'pos.open-tab.read', module: 'pos', resource: 'open-tab', action: 'read', level: 'endpoint', description: 'View Open Tab (pos)' },
  { code: 'pos.layaway.create', module: 'pos', resource: 'layaway', action: 'create', level: 'endpoint', description: 'Create Layaway (pos)' },
  { code: 'pos.layaway.read', module: 'pos', resource: 'layaway', action: 'read', level: 'endpoint', description: 'View Layaway (pos)' },
  { code: 'pos.report.read', module: 'pos', resource: 'report', action: 'read', level: 'endpoint', description: 'View Report (pos)' },
  { code: 'procurement.purchase-order.update', module: 'procurement', resource: 'purchase-order', action: 'update', level: 'endpoint', description: 'Update Purchase Order (procurement)' },
  { code: 'procurement.purchase-receipt.create', module: 'procurement', resource: 'purchase-receipt', action: 'create', level: 'endpoint', description: 'Create Purchase Receipt (procurement)' },
  { code: 'procurement.vendor.manage', module: 'procurement', resource: 'vendor', action: 'manage', level: 'endpoint', description: 'Manage Vendor (procurement)' },
  { code: 'admin.sync.read', module: 'admin', resource: 'sync', action: 'read', level: 'endpoint', description: 'View Sync (admin)' },
  { code: 'admin.sync.create', module: 'admin', resource: 'sync', action: 'create', level: 'endpoint', description: 'Create Sync (admin)' },
  { code: 'reporting.read', module: 'reporting', resource: 'general', action: 'read', level: 'endpoint', description: 'View Reporting module (legacy coarse permission)' },
  { code: 'reporting.create', module: 'reporting', resource: 'general', action: 'create', level: 'endpoint', description: 'Create Reporting module (legacy coarse permission)' },
  { code: 'saas.read', module: 'saas', resource: 'general', action: 'read', level: 'endpoint', description: 'View Saas module (legacy coarse permission)' },
  { code: 'saas.create', module: 'saas', resource: 'general', action: 'create', level: 'endpoint', description: 'Create Saas module (legacy coarse permission)' },
  { code: 'sales.order.create', module: 'sales', resource: 'order', action: 'create', level: 'endpoint', description: 'Create Order (sales)' },
  { code: 'sales.order.update', module: 'sales', resource: 'order', action: 'update', level: 'endpoint', description: 'Update Order (sales)' },
  { code: 'sales.quotation.update', module: 'sales', resource: 'quotation', action: 'update', level: 'endpoint', description: 'Update Quotation (sales)' },
  { code: 'crm.commission.read', module: 'crm', resource: 'commission', action: 'read', level: 'endpoint', description: 'View commission plans, gamification leaderboards/badges/streaks, and payouts (crm)' },
  { code: 'crm.commission.update', module: 'crm', resource: 'commission', action: 'update', level: 'endpoint', description: 'Recompute gamification leaderboards/streaks and evaluate badge awards (crm)' },
  { code: 'crm.commission.manage', module: 'crm', resource: 'commission', action: 'update', level: 'endpoint', description: 'Manage commission plans, tiers, SPIFFs, badges, and payout approval/payment (crm)' },
  { code: 'crm.coaching.read', module: 'crm', resource: 'coaching', action: 'read', level: 'endpoint', description: 'View coaching rubrics, call scorecards, and coaching dashboards (crm)' },
  { code: 'crm.coaching.create', module: 'crm', resource: 'coaching', action: 'create', level: 'endpoint', description: 'Score a call against a coaching rubric (crm)' },
  { code: 'crm.coaching.update', module: 'crm', resource: 'coaching', action: 'update', level: 'endpoint', description: 'Acknowledge a coaching scorecard (rep-side) (crm)' },
  { code: 'crm.coaching.manage', module: 'crm', resource: 'coaching', action: 'update', level: 'endpoint', description: 'Manage coaching rubrics and the coaching library (crm)' },
  { code: 'crm.dealroom.read', module: 'crm', resource: 'dealroom', action: 'read', level: 'endpoint', description: 'View deal rooms, mutual action plan milestones, and stakeholder maps (crm)' },
  { code: 'crm.dealroom.create', module: 'crm', resource: 'dealroom', action: 'create', level: 'endpoint', description: 'Create a deal room for an opportunity (crm)' },
  { code: 'crm.dealroom.update', module: 'crm', resource: 'dealroom', action: 'update', level: 'endpoint', description: 'Manage deal room milestones, stakeholders, documents, and archival (crm)' },
  { code: 'reporting.saved-views.read', module: 'reporting', resource: 'saved-views', action: 'read', level: 'endpoint', description: 'View saved list views' },
  { code: 'reporting.saved-views.create', module: 'reporting', resource: 'saved-views', action: 'create', level: 'endpoint', description: 'Create/update saved list views' },
  { code: 'reporting.saved-views.delete', module: 'reporting', resource: 'saved-views', action: 'delete', level: 'endpoint', description: 'Delete saved list views' },
];

// ── Query helpers (role editor / access-control UI) ──

/** Every permission definition registered for a given module. */
export function getPermissionsByModule(module: string): PermissionDefinition[] {
  return PERMISSION_REGISTRY.filter((p) => p.module === module);
}

/** Distinct `category` labels present for a module, in first-seen order. Modules
 * without categorized permissions (i.e. all `category: undefined`) return []. */
export function getCategoriesForModule(module: string): string[] {
  const seen: string[] = [];
  for (const p of PERMISSION_REGISTRY) {
    if (p.module === module && p.category && !seen.includes(p.category)) seen.push(p.category);
  }
  return seen;
}

/** Permission definitions for a module scoped to one category. */
export function getPermissionsByCategory(module: string, category: string): PermissionDefinition[] {
  return PERMISSION_REGISTRY.filter((p) => p.module === module && p.category === category);
}
