name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    uses: kannan19302/unierp-workspace/.github/workflows/publish-library.yml@main
    permissions:
      contents: read
      id-token: write
